### ISSUE TITLE
Current automenu 'list-group' doesn't support link hover states.

### ISSUE THREAD

**Issue by peshi** [phiamo/MopaBootstrapBundle#1057]
There should be an option to be able to decorate automenu 'list-group' with div instead of ul in order to benefit from Bootstraps linked list items.

Ref: https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_list-group.scss#L41

Example.

```
<div class="list-group">
   <a href="#" class="list-group-item">Link1</a>
   <a href="#" class="list-group-item active">Link2</a>
   <a href="#" class="list-group-item">Link3</a>
</div>
```

**Comment by peshi** [comment]
An example of how to accomplish the above with knp_menu_render

https://gist.github.com/peshi/82997acb75cd1107c959

**Comment by phiamo** [comment]
should we extend the template?

**Comment by peshi** [comment]
@phiamo I'll check so that it doesn't interfere with intended behaviour of automenu and create a PR.

**Comment by phiamo** [comment]
@peshi thanks a lot!

**Comment by phiamo** [comment]
@peshi did we already merge a pr for this ?

**Comment by peshi** [comment]
@phiamo Nope, that hasn't been merged, if I remember correctly we have to lift the 'list-group' from automenu and extend the template to replace <ul>'s for <div>'s.

**Comment by phiamo** [comment]
@peshi is there a PR

**Comment by peshi** [comment]
@phiamo Hi, I have a solution locally (twig based) - but it will replace the current implementation that is specified MenuDecorator and MenuConverter. I would like to get some input from the contributor of automenu regarding this issue, maybe there is a way not to use twig.

**Comment by isometriks** [comment]
I had originally created the menu extension and then @phiamo created the auto menu I believe and moved the menu extension to a separate class so it could be used in a couple ways. I think Twig would be the best bet. If you check out: https://github.com/KnpLabs/KnpMenu/blob/master/src/Knp/Menu/Resources/views/knp_menu.html.twig#L25

We could override that block and change the `ul` to be a variable like `list_element` and then in the `item` block we could have like a `child_element` and be able to pass what it should be rendered as. This almost might be a better PR to KnpMenuBundle instead as we'd have to override that whole block. I don't think this can be done without changing the Twig template because the `ul` and `li` elements are hard coded in it.
