### ISSUE TITLE
Symlink issue

### ISSUE THREAD

**Issue by redactuk** [phiamo/MopaBootstrapBundle#1079]
Installing v3.0.0-beta3 as part of sonatademo dist, composer install reports:

An error occurred while creating symlinkC:\wamp\sandbox\vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle\Resources\public\boostrap

Install is on Window Wamp setup. Any ideas?

**Comment by phiamo** [comment]
@redactuk can you please switch to RC1 there were several improvements to the symlinking

**Comment by incrediblecube** [comment]
Same problem here: getting a permission denied while using `unlink`.
Since the target of the symlink is a folder `unlink` won't work on Windows and the deletion will need some special handling.
Problem occurs in `BaseBootstrapSymlinkCommand` on line 65 (dev-master and all other versions as far as I can see).

This might do the trick:
```php
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' && is_dir($linkTarget)) {
	rmdir($symlinkName);
} else {
	unlink($symlinkName);
}
```

**Comment by phiamo** [comment]
@incrediblecube can you create a PR for this?

**Comment by isometriks** [comment]
Will the Filesystem component help fix that instead of adding it ourselves?

**Comment by MisatoTremor** [comment]
It does. The implementation differs, but in the end it should do the same as the Code shown above: https://github.com/symfony/Filesystem/blob/master/Filesystem.php#L169

It used to check if running Windows (``defined('PHP_WINDOWS_VERSION_MAJOR')``), but uses a directory separator format check (``'\\' === DIRECTORY_SEPARATOR``) instead since version 2.3.24.

**Comment by phiamo** [comment]
closing this issue in favor of #1095 and restarted travis
