### ISSUE TITLE
missing basic form form-group size

### ISSUE THREAD

**Issue by peshi** [phiamo/MopaBootstrapBundle#1133]
creating custom forms using form_row(form.name) without form-horizontal does not have the possibility to use form-group wrapper sizes.

desired output

```
<div class="row">
    <div class="form-group col-xs-4">
        <label for="postcode" class="optional">Postcode</label>
        <input class="form-control" name="postcode" type="text">
    </div>
    <div class="form-group col-xs-8">
        <label for="city" class="optional">City</label>
        <input class="form-control" name="city" type="text">
    </div>
</div>
```

Also, the example of basic forms in sandbox is incorrect due to the fact that basic forms have labels on top of the input.

**Comment by isometriks** [comment]
I'm not sure if this should be added. Does it work to just wrap the groups in columns?

```html
<div class="col-xs-4">
    <div class="form-group">
        ....
    </div>
</div>
```

You can also just render the label and widget explicitly:

```jinja
<div class="row">
    <div class="form-group col-xs-4">
        {{ form_label(form.postcode) }}
        {{ form_widget(form.postcode) }}
    </div>
   ...
</div>
```

If we keep adding in new ways to alter the forms it's going to get really confusing. There's already tons of things you can customize which might be overkill anyway.

**Comment by peshi** [comment]
I'm closing here and adding locally - I do agree with the reasoning.

**Comment by phiamo** [comment]
basicly i would agree too, but,
would it make sense to reduce the feautureset and consolitate it especially looking at bs 4.0 ? what is the main purpuse of the bundle? i see it as a helper for reapeatedly used bs things in symfony , but could we even go futher and reduce the featureset for bs4 while probably creating a own library which could be useful to other frameworks too?

**Comment by isometriks** [comment]
@phiamo I would say yes. I think we need to adhere to some more best practices. We would need to open a discussion about including the external libraries and if we want to possibly include something like https://github.com/Spea/SpBowerBundle, I haven't researched in a while so there might be better solutions but I am not crazy about embedding 3rd party libraries in the repository. It creates a headache for us, and it limits people who want to use it in their projects before we get a chance to update it. 

I'd also like to probably remove the base templates as well with assetic tags built in. I see this issue fairly often in the issues where you have to add this bundle to assetic and then once you do that it will compile stylesheets from those that may not even be used etc. I think I still may like the idea of adding the asset to the assetic configuration if turned on so you can do things like:

```jinja
{% stylesheets '@bootstrap' %}
...
{% endstylesheets %}
```

And otherwise if you wanted to override any part of bootstrap you would just use your own less files. We could provide documentation to set that up / boilerplate. If people want to start a project that has the template files and these things already setup we can do like symfony-standard (I think you have the bootstrap-standard that we could move these too in the app folder) that creates a project that has these already in your `app` folder so you can edit them directory or extend if you want. We can have things like the flashed be an include so you don't need to use the bootstrap-standard but you could still include certain templates from the bundle. Just don't encourage any direct extension as the base template from this bundle. 

I don't know what the most common use-case of the bundle is but I personally only really use it for forms, icons, and sometimes menus. I do still also think that creating some templates for commonly used bootstrap components would be useful as I think I had mentioned a while ago, so doing like:

```jinja
{% embed '@MopaBootstrap/Components/Panel.html.twig' %}
    {% block title %}Panel Title{% endblock %}
    {% block content %}
        Panel Content
    {% endblock %}
{% endembed %}
```

Would be useful to people as a shortcut. 

It is nice being able to customize a lot of things from the form config options, but the more things we try to incorporate programmatically the messier the fields.html.twig gets and has much more logic and becomes harder to maintain and test. I know that some of these changes may make the learning curve a little steeper, but I think encouraging some best practices would be beneficial to a lot of people, and probably reduce issues and PRs on our end due to other libraries changing. 

I would also vote to drop the support for the <3.2 vs >3.2 problems with sass. Then again, what I'm kind of suggesting should fix those anyway as we wouldn't provide those includes to users. They would get the paths themselves (which we could help them do through documentation). I think we can also drop initializr support in configuration and wherever else. 

I think we could also tag 3.0 now. Might as well give a good stable tag for the time being and either let master start targeting 4.0 with these reductions or just start a 4.0 branch and move in when more ready. I am wary that people (including myself) are targeting `dev-master@dev` as we don't have stable besides the RCs recently so we should get on with that so people can at least switch to `~3.0@dev`.
