### ISSUE TITLE
Integration with Silex

### ISSUE THREAD

**Issue by EvilKraft** [phiamo/MopaBootstrapBundle#1157]
Please help me integrate MopaBootstrapBundle into Silex

**Comment by jonny827** [comment]
I have never used Silex. However, as it has been developed by the same developer as Symfony, and it is intended to be a a related micro-framework I believe it is possible.  

While on a related thread [Should Symfony integrate Twitter Bootstrap Form Templates Discussion](https://github.com/symfony/symfony/pull/10272)  I read that "this code should not belong to a bundle, because it is not re-usable (in a silex application for instance)." by Lyrixx  and "bundle templates/resources/code are reusable into silex. They just aren't auto discovered and you can't register its bundle." by docteurklein.  These comments assure me that my thought process about the overlap in bundle usage exists between both frameworks. 

 I also a few days ago did some reasearch on it after seeing your unanswered Issue.  Since a bundle is just a directory structure and set of configuration files, you should be able to reuse it easily in other code.   I ran across someone who has a similar issue to you a couple years ago who blogged about it here [ Tutortial Blogpost Integrating Silex and Braincrafted Bootstrap Bundle](https://mrgierer.wordpress.com/2014/02/16/bootstrap-themed-forms-with-silex/) which is very similar to MopaBootstrap Bundle.   

Although this is not specific details on how to do it as again I have never used Silex and do not fully understand how it works, I hope it points you in the right direction or possibly to a person who may better assist you from the resources I have linked you to. Goodluck!    

Please post your solution if you find one. We could possibly post in in the Documentation to help others who may be interested in using it in Silex.   

If you have found another solution and no longer need this Issue open, please close it.  Thank you !

**Comment by phiamo** [comment]
hi folks thanks for pointing out, we also were discussing splitting this bundle into a library with reusable code and a bundle with symfony specific features, maybe that would help further

**Comment by jonny827** [comment]
Great timing @phiamo.  I was just creating an Issue to discuss this topic.   @EvilKraft If you are interested in following, commenting, and or helping out please check out [MopaBoostrap Documentation / Future of MopaBootStrap #47](https://github.com/phiamo/MopaBootstrapSandboxBundle/issues/47)

**Comment by EvilKraft** [comment]
Hi @jonny827. Thank you for your advice, but I created the issue before I had already read that article. And it was not help me.
