### ISSUE TITLE
Composer error with mopa:bootstrap:symlink:less

### ISSUE THREAD

**Issue by ovgray** [phiamo/MopaBootstrapBundle#298]
When I run the command mopa:bootstrap:symlink:less as administrator on Windows Vista with latest version of Composer (version 6bd7ca0) installed I get this output:

```
c:\xampp\htdocs\xxxx>php app/console mopa:bootstrap:symlink:less
'which' is not recognized as an internal or external command,
operable program or batch file.
PHP Fatal error:  Cannot redeclare class Composer\Autoload\ClassLoader in phar://C:/xampp   htdocs/xxxx/composer.phar/vendor/composer/ClassLoader.php on line 44

Fatal error: Cannot redeclare class Composer\Autoload\ClassLoader in phar://C:/xampp/htdocs/xxxx/composer.phar/vendor/composer/ClassLoader.php on line 44
```

I can successfully run 

```
mopa:bootstrap:symlink:less --manual [pathToTwitterBootstrap] [pathToMopaBootstrapBundle]
```

(after figuring out the correct paths) So it appears to be a problem with the way the command uses Composer. I did not have this problem with the command when I had an earlier version of Composer (version 65e95ed)

**Comment by rohrzange** [comment]
On Windows if php app/console mopa:bootstrap:symlink:less/sass

**Comment by rohrzange** [comment]
I just stumbled across the same issue and fixed it like this:

For MS Windows: 
if 
php app/console mopa:bootstrap:symlink:less
fails it might be a better idea to create the symlink manually with pure Windows OS commands (after all the command above does roughly the same I think). 
So on MS Windows do the following to let MopaBootstrapBundle find the bootstrap files in order to import them correctly:
command prompt as admin
navigate to folder "Resources" in MopaBootstrapBundle
mklink /D bootstrap [PathToTwitterBootstrap]

This creates a symlink called "bootstrap" in MopaBootstrapBundle's "Resources" folder pointing to your twitter bootstrap files. Of course you can use a relative or an absolute path.
